[book]
authors = ["The neo-rs contributors"]
language = "en"
multilingual = false
src = "book"
title = "Neo.rs: The neo Library for Rust"
description = "A book on all things neo-rs"

[output.html]
git-repository-url = "https://github.com/R3E-Network/neo-rs"
default-theme = "ayu"
no-section-label = true

[output.html.fold]
enable = true
level = 1

[build]
build-dir = "target/book"

[preprocessor.template]
before = [ "links" ]

[preprocessor.index]

[preprocessor.links]

